# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrczoom_toolbar(wx.ToolBar):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreToolBar()
        self.PreCreate(pre)
        get_resources().LoadOnToolBar(pre, parent, "zoom_toolbar")
        self.PostCreate(pre)

        # Define variables for the controls


class xrchistory_toolbar(wx.ToolBar):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreToolBar()
        self.PreCreate(pre)
        get_resources().LoadOnToolBar(pre, parent, "history_toolbar")
        self.PostCreate(pre)

        # Define variables for the controls


class xrcMainFrame(wx.Frame):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MainFrame")
        self.PostCreate(pre)

        # Define variables for the controls
        self.frame_1_menubar = xrc.XRCCTRL(self, "frame_1_menubar")
        self.file = xrc.XRCCTRL(self, "file")
        self.pathmanager = self.FindItemById(xrc.XRCID("pathmanager"))
        self.fontchoice = self.FindItemById(xrc.XRCID("fontchoice"))
        self.wxID_EXIT = self.FindItemById(xrc.XRCID("wxID_EXIT"))
        self.options = xrc.XRCCTRL(self, "options")
        self.windows = xrc.XRCCTRL(self, "windows")
        self.menu_default_layout = self.FindItemById(xrc.XRCID("menu_default_layout"))
        self.menu_toolbars = xrc.XRCCTRL(self, "menu_toolbars")
        self.gui_debug_menu = xrc.XRCCTRL(self, "gui_debug_menu")
        self.gui_html_ide = self.FindItemById(xrc.XRCID("gui_html_ide"))
        self.gui_widget_inspector = self.FindItemById(xrc.XRCID("gui_widget_inspector"))
        self.help = xrc.XRCCTRL(self, "help")
        self.wxID_ABOUT = self.FindItemById(xrc.XRCID("wxID_ABOUT"))
        self.main_toolbar = xrc.XRCCTRL(self, "main_toolbar")
        self.statusbar = xrc.XRCCTRL(self, "statusbar")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('auifrm.xrc')
