# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcCopyVerseDialog(wx.Dialog):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "CopyVerseDialog")
        self.PostCreate(pre)

        # Define variables for the controls
        self.reference = xrc.XRCCTRL(self, "reference")
        self.gui_template_list = xrc.XRCCTRL(self, "gui_template_list")
        self.collapsible_panel = xrc.XRCCTRL(self, "collapsible_panel")
        self.tp_holder = xrc.XRCCTRL(self, "tp_holder")
        self.tp_holder = xrc.XRCCTRL(self, "tp_holder")
        self.gui_save_template = xrc.XRCCTRL(self, "gui_save_template")
        self.gui_load_template = xrc.XRCCTRL(self, "gui_load_template")
        self.preview = xrc.XRCCTRL(self, "preview")
        self.wxID_OK = xrc.XRCCTRL(self, "wxID_OK")
        self.wxID_CANCEL = xrc.XRCCTRL(self, "wxID_CANCEL")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('copyverses.xrc')
