# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcframe_1_menubar(wx.MenuBar):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreMenuBar()
        self.PreCreate(pre)
        get_resources().LoadOnMenuBar(pre, parent, "frame_1_menubar")
        self.PostCreate(pre)

        # Define variables for the controls
        self.File = xrc.XRCCTRL(self, "File")
        self.randomverse = self.FindItemById(xrc.XRCID("randomverse"))
        self.wxID_EXIT = self.FindItemById(xrc.XRCID("wxID_EXIT"))
        self.Options = xrc.XRCCTRL(self, "Options")
        self.swordloc = self.FindItemById(xrc.XRCID("swordloc"))
        self.defaultmod = self.FindItemById(xrc.XRCID("defaultmod"))
        self.Help = xrc.XRCCTRL(self, "Help")
        self.wxID_ABOUT = self.FindItemById(xrc.XRCID("wxID_ABOUT"))


class xrcHarmonyFrame(wx.Frame):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "HarmonyFrame")
        self.PostCreate(pre)

        # Define variables for the controls
        self.harmony_notebook = xrc.XRCCTRL(self, "harmony_notebook")


class xrcHarmonyPanel(wx.Panel):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "HarmonyPanel")
        self.PostCreate(pre)

        # Define variables for the controls
        self.splitter_window = xrc.XRCCTRL(self, "splitter_window")
        self.pericope_list = xrc.XRCCTRL(self, "pericope_list")
        self.harmony_toolbar = xrc.XRCCTRL(self, "harmony_toolbar")
        self.tool_bible_ref = xrc.XRCCTRL(self, "tool_bible_ref")
        self.bible_text = xrc.XRCCTRL(self, "bible_text")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('harmonyfrm.xrc')
