# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcSourcesPanel(wx.Panel):
#!XRCED:begin-block:xrcSourcesPanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcSourcesPanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "SourcesPanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.sources_list = xrc.XRCCTRL(self, "sources_list")
        self.toolbar_panel = xrc.XRCCTRL(self, "toolbar_panel")
        self.properties_panel = xrc.XRCCTRL(self, "properties_panel")
        self.source_name = xrc.XRCCTRL(self, "source_name")
        self.source_location = xrc.XRCCTRL(self, "source_location")
        self.directory_picker = xrc.XRCCTRL(self, "directory_picker")
        self.directory = xrc.XRCCTRL(self, "directory")
        self.gui_passive_ftp = xrc.XRCCTRL(self, "gui_passive_ftp")
        self.wxID_OK = xrc.XRCCTRL(self, "wxID_OK")
        self.wxID_CANCEL = xrc.XRCCTRL(self, "wxID_CANCEL")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('installmgr_sources.xrc')
