# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcManageTopicsFrame(wx.Frame):
#!XRCED:begin-block:xrcManageTopicsFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcManageTopicsFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "ManageTopicsFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.toolbar = xrc.XRCCTRL(self, "toolbar")
        self.splitter = xrc.XRCCTRL(self, "splitter")
        self.topic_tree = xrc.XRCCTRL(self, "topic_tree")
        self.passage_list_ctrl = xrc.XRCCTRL(self, "passage_list_ctrl")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('manage_topics.xrc')
