# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcModuleManagerDialog(wx.Dialog):
#!XRCED:begin-block:xrcModuleManagerDialog.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcModuleManagerDialog.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "ModuleManagerDialog")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.filterable_tree_holder = xrc.XRCCTRL(self, "filterable_tree_holder")
        self.gui_delete = xrc.XRCCTRL(self, "gui_delete")
        self.gui_unlock = xrc.XRCCTRL(self, "gui_unlock")
        self.wxID_OK = xrc.XRCCTRL(self, "wxID_OK")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('module_manager.xrc')

# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Delete")
    _("Unlock")
    _("Manage books")

