# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcMovableListPanel(wx.Panel):
#!XRCED:begin-block:xrcMovableListPanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcMovableListPanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "MovableListPanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.gui_templates = xrc.XRCCTRL(self, "gui_templates")
        self.move_top = xrc.XRCCTRL(self, "move_top")
        self.move_up = xrc.XRCCTRL(self, "move_up")
        self.move_down = xrc.XRCCTRL(self, "move_down")
        self.move_bottom = xrc.XRCCTRL(self, "move_bottom")
        self.gui_add = xrc.XRCCTRL(self, "gui_add")
        self.gui_edit = xrc.XRCCTRL(self, "gui_edit")
        self.gui_remove = xrc.XRCCTRL(self, "gui_remove")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('movablelist.xrc')

# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Move item to top")
    _("Move item up")
    _("Move item down")
    _("Move item to bottom")
    _("Add a new item")
    _("Edit this item")
    _("Remove this item")

