# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcbutton_bar(wx.ToolBar):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreToolBar()
        self.PreCreate(pre)
        get_resources().LoadOnToolBar(pre, parent, "button_bar")
        self.PostCreate(pre)

        # Define variables for the controls


class xrcpanel(wx.Panel):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "panel")
        self.PostCreate(pre)

        # Define variables for the controls
        self.move_up = xrc.XRCCTRL(self, "move_up")
        self.move_down = xrc.XRCCTRL(self, "move_down")
        self.gui_copy = xrc.XRCCTRL(self, "gui_copy")
        self.gui_rename = xrc.XRCCTRL(self, "gui_rename")
        self.gui_remove = xrc.XRCCTRL(self, "gui_remove")


class xrcMovableListPanel(wx.Panel):
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "MovableListPanel")
        self.PostCreate(pre)

        # Define variables for the controls
        self.gui_templates = xrc.XRCCTRL(self, "gui_templates")
        self.move_top = xrc.XRCCTRL(self, "move_top")
        self.move_up = xrc.XRCCTRL(self, "move_up")
        self.move_down = xrc.XRCCTRL(self, "move_down")
        self.move_bottom = xrc.XRCCTRL(self, "move_bottom")
        self.gui_add = xrc.XRCCTRL(self, "gui_add")
        self.gui_edit = xrc.XRCCTRL(self, "gui_edit")
        self.gui_remove = xrc.XRCCTRL(self, "gui_remove")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('movablelist.xrc')
