# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcTemplateManager(wx.Dialog):
#!XRCED:begin-block:xrcTemplateManager.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcTemplateManager.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "TemplateManager")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.movable_list_holder = xrc.XRCCTRL(self, "movable_list_holder")
        self.gui_preview = xrc.XRCCTRL(self, "gui_preview")
        self.tp_holder = xrc.XRCCTRL(self, "tp_holder")
        self.wxID_OK = xrc.XRCCTRL(self, "wxID_OK")
        self.wxID_CANCEL = xrc.XRCCTRL(self, "wxID_CANCEL")



class xrcTemplatePanel(wx.Panel):
#!XRCED:begin-block:xrcTemplatePanel.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcTemplatePanel.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "TemplatePanel")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.header = xrc.XRCCTRL(self, "header")
        self.body = xrc.XRCCTRL(self, "body")
        self.footer = xrc.XRCCTRL(self, "footer")
        self.headings = xrc.XRCCTRL(self, "headings")
        self.instructions = xrc.XRCCTRL(self, "instructions")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('templatemanager.xrc')

# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Template Manager")
    _("Preview")
    _("&Ok")
    _("&Cancel")
    _("&Header")
    _("&Body")
    _("$$text ")
    _("&Footer")
    _("\n$$range ($$version)")
    _("&Headings")
    _("<h5>$$heading</h5>")
    _("Use $$text for the text of a verse, $$versenumber for the\nverse number and $$range for the reference.")

